# -*- coding: utf-8 -*-
"""HFMD_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H4vzXzcBlyMNmKLtll9UaC-IaT_2NJxK
"""

import numpy as np
from numpy import *
import pandas as pd
from scipy import stats
from scipy.stats import sem
import seaborn as sns; sns.set_theme()
import matplotlib as mpl
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

df_rsv = pd.read_csv('/content/drive/MyDrive/Infectious Diseases/HFMD/data/HFMD_RSV/raw_rsv/rsv_total.csv')
df_cases = pd.read_csv('/content/drive/MyDrive/Infectious Diseases/HFMD/data/report_cases/report_cases_total.csv')

df_rsv = df_rsv[1:53]
df_cases = df_cases[1:53]

ls = [2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021]
lr = []
for i in ls:
  r = np.corrcoef(df_rsv[f'topic_{i}'], df_cases[f'{i}'])
  r = round(r[0][1],3)
  lr.append(r)
  print(f'{i}:{r}')

sum(lr)/18

sem(lr)

## bar correlation

plt.figure(figsize=(20,8))
plt.rcParams['axes.facecolor'] = 'w'

bar_1 = plt.bar(range(len(lr)),lr,color='#3C5488FF',tick_label=ls)

lr_1 = [0.562,0,0,0,0.236,0,0,0,0,0,0,0,0,0,0,0,0.338,0]
# bar_2 = plt.bar(range(len(lr_1)),lr_1,color='#F39B7FFF',tick_label=ls)

# plt.legend([bar_1,bar_2],['r<0.7','r≥0.7'],loc='upper right')


plt.xlabel('Year',fontsize=18,labelpad=15)
plt.ylabel('Pearson correlation coefficient (r)',fontsize=18,labelpad=15)
plt.title("Correlation between actual HFMD cases and HFMD's Interest search RSV from 2004 to 2021",fontsize=22,pad=40,loc='center')
plt.tick_params(labelsize=15)

my_y_ticks = np.arange(0,1.1,0.1)
plt.yticks(my_y_ticks)
plt.ylim(0,1.0)

plt.gca().spines['bottom'].set_color('black')
plt.gca().spines['left'].set_color('black')

plt.axhline(y=0.7,linewidth=4, color='black',linestyle='--')

# plt.savefig('/content/drive/MyDrive/Infectious Diseases/HFMD/Figures/bar_correlation.png',bbox_inches='tight')
plt.show()

df_1 = pd.read_csv('/content/drive/MyDrive/Infectious Diseases/HFMD/data/HFMD_rsv.csv')
df_2 = pd.read_csv('/content/drive/MyDrive/Infectious Diseases//HFMD/data/cases.csv')

df_1

df_2

## trends from 2004 to 2021

fig, ax = plt.subplots(2, 1,figsize=(20,8))

a1, = ax[0].plot(range(950),df_2['cases'],color='#3C5488FF',label='HFMD cases',linewidth=2)
a2, = ax[1].plot(range(221),df_1['topic'],color='#E64B35FF',label='HFMD RSV',linewidth=2)

ax[1].set_xlabel('Year',fontsize=15,labelpad=15)
ax[0].set_ylabel('Actual cases',fontsize=15,labelpad=13)
ax[1].set_ylabel('RSV',fontsize=15,labelpad=20)
ax[0].set_title('Changes of HFMD actual cases and Internet search RSV from 2004 to 2021',fontsize=20,pad=35,loc='center')

ax[0].patch.set_facecolor('w')
ax[1].patch.set_facecolor('w')

_xticks = [f'200{i}' for i in range(4,10)]
_xticks += [f'20{i}' for i in range(10,22)]
plt.setp(ax[0], xticks=list(range(950))[::52], xticklabels=_xticks)

ax[0].axis('on')
plt.setp(ax[1], xticks=list(range(221))[::12], xticklabels=_xticks)
plt.setp(ax[0], xticks=list(range(950))[::52], xticklabels=[])

ax[0].legend(loc='upper left')
ax[1].legend(loc='upper left')
ax[1].tick_params(axis='both', labelsize=14)

ax[0].spines['bottom'].set_color('black')
ax[0].spines['left'].set_color('black')
ax[1].spines['bottom'].set_color('black')
ax[1].spines['left'].set_color('black')

ax[0].tick_params(axis='both', labelsize=14)
ax[1].tick_params(axis='both', labelsize=14)

ax[0].set_xlim(0,950)
ax[0].set_ylim(bottom=0)
ax[1].set_xlim(0,221)
ax[1].set_ylim(0,101)

# dashline
ax[0].plot((568, 568), (0, 40000), '--',linewidth=2, color='grey')
ax[0].plot((828, 828), (0, 40000), '--',linewidth=2, color='grey')
ax[0].plot((949, 949), (0, 40000), '--',linewidth=2, color='grey')

ax[1].plot((132, 132), (0, 100), '--',linewidth=2, color='grey')
ax[1].plot((192, 192), (0, 100), '--',linewidth=2, color='grey')
ax[1].plot((220, 220), (0, 100), '--',linewidth=2, color='grey')

# text
ax[0].text(670,40000,'Period 1',fontsize=16)
ax[0].text(860,40000,'Period 2',fontsize=16)


plt.show()

# fig.savefig('/content/drive/MyDrive/Infectious Diseases//HFMD/Figures/trends.png',bbox_inches='tight')

(plt.gca())

"""## **Heatmap**"""

## heatmap

# mean = np.mean(lr)
# std = np.std(lr)
# conf_interval = stats.norm.interval(0.95,loc=mean,scale=std)

# conf_interval

# ls_coe = []
# for i in ls:
#   ls_r = []
#   ls_coe.append(ls_r)
#   for j in ls:  
#     r = np.corrcoef(df_rsv[f'topic_{i}'],df_cases[f'{j}'])[0][1]
#     print(r)
#     ls_r.append(r)

# ls_coe = []
# for i in ls:
#   ls_r = []
#   ls_coe.append(ls_r)
#   for j in ls:  
#     r = np.corrcoef(df_rsv[f'term_{i}'],df_cases[f'{j}'])[0][1]
#     print(r)
#     ls_r.append(r)

# ls_index = ['2004_rsv','2005_rsv','2006_rsv','2007_rsv','2008_rsv','2009_rsv','2010_rsv','2011_rsv','2012_rsv','2013_rsv','2014_rsv','2015_rsv','2016_rsv','2017_rsv','2018_rsv','2019_rsv','2020_rsv','2021_rsv']
# df_coe = pd.DataFrame(ls_coe,columns=ls,index=ls_index)

# from seaborn.matrix import heatmap
# ax = sns.heatmap(df_coe)
# heatmap = ax.get_figure()

# ls_coe = []
# for i in ls:
#   ls_r = []
#   ls_coe.append(ls_r)
#   for j in ls:  
#     r = np.corrcoef(df_cases[f'{i}'],df_cases[f'{j}'])[0][1]
#     # print(r)
#     ls_r.append(r)
  
# # ls_index = ['2004_rsv','2005_rsv','2006_rsv','2007_rsv','2008_rsv','2009_rsv','2010_rsv','2011_rsv','2012_rsv','2013_rsv','2014_rsv','2015_rsv','2016_rsv','2017_rsv','2018_rsv','2019_rsv','2020_rsv','2021_rsv']
# df_coe = pd.DataFrame(ls_coe,columns=ls,index=ls)

# from seaborn.matrix import heatmap
# ax = sns.heatmap(df_coe)
# heatmap = ax.get_figure()

# ls_coe = []
# for i in ls:
#   ls_r = []
#   ls_coe.append(ls_r)
#   for j in ls:  
#     r = np.corrcoef(df_rsv[f'topic_{i}'],df_rsv[f'topic_{j}'])[0][1]
#     # print(r)
#     ls_r.append(r)
  
# ls_index = ['2004_rsv','2005_rsv','2006_rsv','2007_rsv','2008_rsv','2009_rsv','2010_rsv','2011_rsv','2012_rsv','2013_rsv','2014_rsv','2015_rsv','2016_rsv','2017_rsv','2018_rsv','2019_rsv','2020_rsv','2021_rsv']
# df_coe = pd.DataFrame(ls_coe,columns=ls_index,index=ls_index)

# from seaborn.matrix import heatmap
# ax = sns.heatmap(df_coe)
# heatmap = ax.get_figure()

# df_cases = df_cases[1:53]
# df_rsv = df_rsv[1:53]

# df_cases = df_cases[['2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019','2020','2021']]
# df_rsv = df_rsv[['topic_2004','topic_2005','topic_2006','topic_2007','topic_2008','topic_2009','topic_2010','topic_2011','topic_2012','topic_2013','topic_2014','topic_2015','topic_2016','topic_2017','topic_2018','topic_2019','topic_2020','topic_2021']]

# x = range(52)
# for z in ls:
#   # y = df_cases[f'{z}']
#   y = df_rsv[f'topic_{z}']
#   plt.plot(x,y)

# df_rsv

# x = range(52)
# y_1 = df_cases['2021']
# y_2 = df_rsv['topic_2021']
# plt.plot(x,y_1)

# x = range(52)
# y_1 = df_cases['2004']
# y_2 = df_rsv['topic_2021']
# plt.plot(x,y_2)

# for i in ls:
#   y_1 = df_cases[f'{i}']
#   y_2 = df_rsv[f'topic_{i}']
#   r = np.corrcoef(y_1,y_2)[0][1]
#   print(f'{i}:{r}')

